---
:shared:
  :appropriate_bodies:
    - body_type
  :blazer_queries:
    - id
    - creator_id
    - name
    - description
    - statement
    - data_source
    - status
    - created_at
    - updated_at
  :blazer_dashboard_queries:
  - id
  - dashboard_id
  - query_id
  - position
  - created_at
  - updated_at
  :blazer_dashboards:
  - id
  - creator_id
  - name
  - created_at
  - updated_at
  :blazer_checks:
  - id
  - creator_id
  - query_id
  - state
  - schedule
  - emails
  - slack_channels
  - check_type
  - message
  - last_run_at
  - created_at
  - updated_at
  :blazer_audits:
  - id
  - user_id
  - query_id
  - statement
  - data_source
  - created_at
  :solid_queue_semaphores:
  - id
  - key
  - value
  - expires_at
  - created_at
  - updated_at
  :cohorts_lead_providers:
  - id
  - lead_provider_id
  - cohort_id
  - created_at
  - updated_at
  :solid_queue_recurring_tasks:
  - id
  - key
  - schedule
  - command
  - class_name
  - arguments
  - queue_name
  - priority
  - static
  - description
  - created_at
  - updated_at
  :solid_queue_processes:
  - id
  - kind
  - last_heartbeat_at
  - supervisor_id
  - pid
  - hostname
  - metadata
  - created_at
  - name
  :solid_queue_pauses:
  - id
  - queue_name
  - created_at
  :solid_queue_jobs:
  - id
  - queue_name
  - class_name
  - arguments
  - priority
  - active_job_id
  - scheduled_at
  - finished_at
  - concurrency_key
  - created_at
  - updated_at
  :solid_queue_scheduled_executions:
  - id
  - job_id
  - queue_name
  - priority
  - scheduled_at
  - created_at
  :solid_queue_recurring_executions:
  - id
  - job_id
  - task_key
  - run_at
  - created_at
  :solid_queue_ready_executions:
  - id
  - job_id
  - queue_name
  - priority
  - created_at
  :solid_queue_failed_executions:
  - id
  - job_id
  - error
  - created_at
  :solid_queue_claimed_executions:
  - id
  - job_id
  - process_id
  - created_at
  :solid_queue_blocked_executions:
  - id
  - job_id
  - queue_name
  - priority
  - concurrency_key
  - expires_at
  - created_at
  :gias_school_links:
  - id
  - urn
  - link_urn
  - link_type
  - link_date
  - created_at
  - updated_at
  :gias_schools:
  - urn
  - name
  - status
  - funding_eligibility
  - address_line1
  - address_line2
  - address_line3
  - postcode
  - primary_contact_email
  - secondary_contact_email
  - opened_on
  - closed_on
  - created_at
  - updated_at
  - administrative_district_name
  - local_authority_code
  - local_authority_name
  - establishment_number
  - phase_name
  - section_41_approved
  - type_name
  - ukprn
  - website
  - induction_eligibility
  - in_england
  :users:
  - id
  - name
  - email
  - otp_secret
  - otp_verified_at
  - created_at
  - updated_at
  - role
  :training_periods:
  - id
  - school_partnership_id
  - started_on
  - finished_on
  - created_at
  - updated_at
  - ect_at_school_period_id
  - mentor_at_school_period_id
  - range
  - ecf_start_induction_record_id
  - ecf_end_induction_record_id
  - expression_of_interest_id
  - training_programme
  - deferred_at
  - deferral_reason
  - withdrawn_at
  - withdrawal_reason
  - schedule_id
  :teacher_migration_failures:
  - id
  - teacher_id
  - model
  - message
  - migration_item_id
  - migration_item_type
  - created_at
  - updated_at
  :schools:
  - last_chosen_appropriate_body_id
  - last_chosen_lead_provider_id
  - last_chosen_training_programme
  - id
  - created_at
  - updated_at
  - api_updated_at
  - urn
  - induction_tutor_name
  - induction_tutor_email
  - api_id
  :school_partnerships:
  - id
  - created_at
  - updated_at
  - lead_provider_delivery_partnership_id
  - school_id
  - api_id
  - api_updated_at
  :teachers:
  - api_id
  - api_ect_training_record_id
  - api_mentor_training_record_id
  - corrected_name
  - trs_first_name
  - trs_last_name
  - mentor_became_ineligible_for_funding_on
  - mentor_became_ineligible_for_funding_reason
  - ect_payments_frozen_year
  - mentor_payments_frozen_year
  - ect_pupil_premium_uplift
  - ect_sparsity_uplift
  - ect_first_became_eligible_for_training_at
  - mentor_first_became_eligible_for_training_at
  - api_updated_at
  :metadata_teachers_lead_providers:
  - id
  - teacher_id
  - lead_provider_id
  - latest_ect_training_period_id
  - latest_mentor_training_period_id
  - latest_ect_contract_period_year
  - latest_mentor_contract_period_year
  - api_mentor_id
  - created_at
  - updated_at
  :pending_induction_submissions:
  - id
  - appropriate_body_id
  - establishment_id
  - trn
  - date_of_birth
  - induction_programme
  - training_programme
  - started_on
  - finished_on
  - number_of_terms
  - created_at
  - updated_at
  - confirmed_at
  - trs_first_name
  - trs_last_name
  - trs_date_of_birth
  - trs_alerts
  - trs_email_address
  - trs_prohibited_from_teaching
  - trs_induction_start_date
  - trs_induction_completed_date
  - trs_induction_status
  - trs_induction_status_description
  - trs_qts_awarded_on
  - trs_qts_status_description
  - trs_initial_teacher_training_end_date
  - trs_initial_teacher_training_provider_name
  - outcome
  - delete_at
  - confirmed
  - pending_induction_submission_batch_id
  - error_messages
  :pending_induction_submission_batches:
  - data
  - error_message
  - file_name
  :migration_failures:
  - id
  - data_migration_id
  - item
  - failure_message
  - created_at
  - updated_at
  - parent_id
  - parent_type
  :mentorship_periods:
  - id
  - ect_at_school_period_id
  - mentor_at_school_period_id
  - started_on
  - finished_on
  - created_at
  - updated_at
  - range
  - ecf_start_induction_record_id
  - ecf_end_induction_record_id
  :mentor_at_school_periods:
  - id
  - school_id
  - teacher_id
  - started_on
  - finished_on
  - created_at
  - updated_at
  - range
  - ecf_start_induction_record_id
  - ecf_end_induction_record_id
  - email
  :lead_providers:
  - id
  - ecf_id
  - name
  - created_at
  - updated_at
  :events:
  - id
  - heading
  - body
  - event_type
  - happened_at
  - teacher_id
  - appropriate_body_id
  - induction_period_id
  - induction_extension_id
  - school_id
  - ect_at_school_period_id
  - mentor_at_school_period_id
  - training_period_id
  - mentorship_period_id
  - school_partnership_id
  - lead_provider_id
  - delivery_partner_id
  - active_lead_provider_id
  - lead_provider_delivery_partnership_id
  - pending_induction_submission_batch_id
  - schedule_id
  - statement_id
  - statement_adjustment_id
  - user_id
  - author_type
  - author_id
  - author_name
  - author_email
  - created_at
  - updated_at
  - metadata
  - modifications
  - zendesk_ticket_id
  :ect_at_school_periods:
  - id
  - school_id
  - teacher_id
  - started_on
  - finished_on
  - created_at
  - updated_at
  - range
  - ecf_start_induction_record_id
  - ecf_end_induction_record_id
  - working_pattern
  - email
  - school_reported_appropriate_body_id
  - training_programme
  :delivery_partners:
  - id
  - name
  - created_at
  - updated_at
  - api_updated_at
  - api_id
  :declarations:
  - id
  - training_period_id
  - declaration_type
  - created_at
  - updated_at
  :data_migrations:
  - id
  - model
  - processed_count
  - failure_count
  - started_at
  - completed_at
  - total_count
  - queued_at
  - worker
  - created_at
  - updated_at
  - cache_stats
  :contract_periods:
  - year
  - created_at
  - updated_at
  - started_on
  - finished_on
  - enabled
  - range
  :active_lead_providers:
  - id
  - lead_provider_id
  - contract_period_year
  - created_at
  - updated_at
  :statement_adjustments:
  - id
  - statement_id
  - ecf_id
  - payment_type
  - amount
  - created_at
  - updated_at
  :statements:
  - id
  - active_lead_provider_id
  - api_id
  - month
  - year
  - deadline_date
  - payment_date
  - marked_as_paid_at
  - fee_type
  - status
  - created_at
  - updated_at
  - api_updated_at
  :api_tokens:
  - id
  - lead_provider_id
  - token
  - description
  - last_used_at
  - created_at
  - updated_at
  :lead_provider_delivery_partnerships:
  - id
  - active_lead_provider_id
  - delivery_partner_id
  - created_at
  - updated_at
  - ecf_id
  :parity_check_runs:
  - id
  - state
  - mode
  - started_at
  - completed_at
  - created_at
  - updated_at
  :parity_check_requests:
  - id
  - run_id
  - lead_provider_id
  - endpoint_id
  - state
  - started_at
  - completed_at
  - created_at
  - updated_at
  :parity_check_responses:
  - id
  - request_id
  - ecf_status_code
  - rect_status_code
  - ecf_body
  - rect_body
  - ecf_time_ms
  - rect_time_ms
  - ecf_request_uri
  - rect_request_uri
  - request_body
  - match_rate
  - page
  - created_at
  - updated_at
  :parity_check_endpoints:
  - id
  - path
  - method
  - options
  - created_at
  - updated_at
  :metadata_schools_lead_providers_contract_periods:
  - id
  - school_id
  - lead_provider_id
  - contract_period_year
  - expression_of_interest_or_school_partnership
  - created_at
  - updated_at
  :metadata_schools_contract_periods:
  - id
  - school_id
  - contract_period_year
  - in_partnership
  - induction_programme_choice
  - created_at
  - updated_at
  :metadata_delivery_partners_lead_providers:
  - id
  - delivery_partner_id
  - lead_provider_id
  - contract_period_years
  - created_at
  - updated_at
  :schedules:
  - id
  - contract_period_year
  - identifier
  - schedule_type
  - created_at
  - updated_at
  :milestones:
  - id
  - schedule_id
  - declaration_type
  - start_date
  - milestone_date
  - created_at
  - updated_at
  :teacher_id_changes:
  - id
  - teacher_id
  - api_from_teacher_id
  - api_to_teacher_id
  - ecf_id
  - created_at
  - updated_at
