get:
  - "/api/v3/statements":
      paginate: true
      exclude:
        - type
  - "/api/v3/statements":
      query:
        filter:
          cohort: 2021
      exclude:
        - type
  - "/api/v3/statements":
      paginate: true
      query:
        filter:
          cohort: "2022,2023"
      exclude:
        - type
  - "/api/v3/statements":
      paginate: true
      query:
        filter:
          cohort: "2022,2023"
          updated_since: "2024-11-13T11:21:55Z"
      exclude:
        - type
  - "/api/v3/statements/:id":
      id: ":statement_id"
      exclude:
        - type
        
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2021
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2022
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2024
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2025
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          urn: "102396"
          cohort: 2023
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
          updated_since: "2025-04-13T11:21:55Z"
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: 2021
          sort: "-updated_at"
      exclude:
        - expression_of_interest
  - "/api/v3/schools":
      ecf_path: "/api/v3/schools/ecf"
      paginate: true
      query:
        filter:
          cohort: "2021,2022"
          urn: "102396"
          updated_since: "2025-04-13T11:21:55Z"
      exclude:
        - expression_of_interest
  - "/api/v3/schools/:id":
      query:
        filter:
          cohort: 2022
      ecf_path: "/api/v3/schools/ecf/:id"
      id: ":school_id"
      exclude:
        - expression_of_interest

  - "/api/v3/delivery-partners":
      paginate: true
  - "/api/v3/delivery-partners":
      paginate: true
      query:
        filter:
          cohort: 2023
  - "/api/v3/delivery-partners":
      paginate: true
      query:
        sort: "-updated_at"
  - "/api/v3/delivery-partners":
      paginate: true
      query:
        filter:
          cohort: 2023
        sort: "+created_at"
  - "/api/v3/delivery-partners/:id":
      id: ":delivery_partner_id"

  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        sort: "-updated_at"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
        sort: "+created_at"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        filter:
          cohort: "2021,2022"
          updated_since: "2025-04-13T11:21:55Z"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        filter:
          updated_since: "2025-04-13T11:21:55Z"
          delivery_partner_id: ":delivery_partner_id"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      paginate: true
      query:
        filter:
          cohort: "2023,2024"
          updated_since: "2025-04-13T11:21:55Z"
          delivery_partner_id: ":delivery_partner_id"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
  - "/api/v3/partnerships/:id":
      ecf_path: "/api/v3/partnerships/ecf/:id"
      id: ":partnership_id"
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status

  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          updated_since: "2025-04-13T11:21:55Z"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          training_status: "withdrawn"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          from_participant_id: ":from_teacher_api_id"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        sort: "-updated_at"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          cohort: 2023
        sort: "+created_at"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          cohort: "2021,2022"
          updated_since: "2025-04-13T11:21:55Z"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          updated_since: "2025-04-13T11:21:55Z"
          training_status: "withdrawn"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants":
      ecf_path: "/api/v3/participants/ecf"
      paginate: true
      query:
        filter:
          cohort: "2023,2024"
          updated_since: "2025-04-13T11:21:55Z"
          training_status: "deferred"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants/:id":
      ecf_path: "/api/v3/participants/ecf/:id"
      id: ":teacher_api_id"
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date

post:
  - "/api/v3/partnerships":
      ecf_path: "/api/v3/partnerships/ecf"
      body: partnership_create_body
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
put:
  - "/api/v3/partnerships/:id":
      ecf_path: "/api/v3/partnerships/ecf/:id"
      id: ":partnership_id"
      body: partnership_update_body
      exclude:
        - participants_currently_training
        - challenged_at
        - challenged_reason
        - status
        
  - "/api/v3/participants/:id/withdraw":
      ecf_path: "/api/v3/participants/ecf/:id/withdraw"
      id: ":active_teacher_api_id_for_participant_action"
      body: active_participant_withdraw_body
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants/:id/withdraw":
      ecf_path: "/api/v3/participants/ecf/:id/withdraw"
      id: ":withdrawn_teacher_api_id_for_participant_action"
      body: withdrawn_participant_withdraw_body
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date

  - "/api/v3/participants/:id/defer":
      ecf_path: "/api/v3/participants/ecf/:id/defer"
      id: ":active_teacher_api_id_for_participant_action"
      body: participant_defer_body
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
  - "/api/v3/participants/:id/defer":
      ecf_path: "/api/v3/participants/ecf/:id/defer"
      id: ":deferred_teacher_api_id_for_participant_action"
      body: deferred_participant_defer_body
      exclude:
        - teacher_reference_number_validated
        - overall_induction_start_date
